name: sikapoke_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  cloud_functions: 5.3.4
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.4.4
  get: ^4.7.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
