// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOkpNLnlTw1okNrl7-IzyUF5zpNcksrE',
    appId: '1:94818912888:web:80fb59ca4fcc8575d3fb8d',
    messagingSenderId: '94818912888',
    projectId: 'sikapokeneo',
    authDomain: 'sikapokeneo.firebaseapp.com',
    storageBucket: 'sikapokeneo.firebasestorage.app',
    measurementId: 'G-6NH3PP3V2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqamxkz4rvbBW536U9xkImAYazbl9yQ8',
    appId: '1:454172092919:android:00f313fa8261e938f7e6f2',
    messagingSenderId: '454172092919',
    projectId: 'sikapoke-42416',
    storageBucket: 'sikapoke-42416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4IqdRc_dKvGzI4b0goucTLzmEmzf_kms',
    appId: '1:454172092919:ios:6ef651f532a9fe67f7e6f2',
    messagingSenderId: '454172092919',
    projectId: 'sikapoke-42416',
    storageBucket: 'sikapoke-42416.firebasestorage.app',
    iosBundleId: 'n',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4IqdRc_dKvGzI4b0goucTLzmEmzf_kms',
    appId: '1:454172092919:ios:5a8b3d57e4cb8f7cf7e6f2',
    messagingSenderId: '454172092919',
    projectId: 'sikapoke-42416',
    storageBucket: 'sikapoke-42416.firebasestorage.app',
    iosBundleId: 'pepe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD364SqFKaTSyR1FGJ7QN2H6CY1wQEA8-g',
    appId: '1:454172092919:web:2ce727529d045e80f7e6f2',
    messagingSenderId: '454172092919',
    projectId: 'sikapoke-42416',
    authDomain: 'sikapoke-42416.firebaseapp.com',
    storageBucket: 'sikapoke-42416.firebasestorage.app',
    measurementId: 'G-FEPMM74719',
  );
}