import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

// Firestore データアップロード用
class DataUploadPage extends StatelessWidget {
  final List<Map<String, dynamic>> cards = [
    {
      "id": 1,
      "name": "ITストラテジスト",
      "type": "IT・パソコン・情報技術",
      "power": 71,
      "rank": "S",
    },
    {
      "id": 2,
      "name": "システム監査技術者",
      "type": "IT・パソコン・情報技術",
      "power": 70,
      "rank": "S",
    },
    {
      "id": 3,
      "name": "プロジェクトマネージャー",
      "type": "IT・パソコン・情報技術",
      "power": 69,
      "rank": "A",
    },
    {
      "id": 4,
      "name": "システムアーキテクト",
      "type": "IT・パソコン・情報技術",
      "power": 68,
      "rank": "A",
    },
    {
      "id": 5,
      "name": "ITサービスマネージャ",
      "type": "IT・パソコン・情報技術",
      "power": 68,
      "rank": "A",
    },
    {
      "id": 6,
      "name": "情報セキュリティスペシャリスト",
      "type": "IT・パソコン・情報技術",
      "power": 67,
      "rank": "A",
    },
    {
      "id": 7,
      "name": "ネットワークスペシャリスト",
      "type": "IT・パソコン・情報技術",
      "power": 67,
      "rank": "A",
    },
    {
      "id": 8,
      "name": "データベーススペシャリスト",
      "type": "IT・パソコン・情報技術",
      "power": 67,
      "rank": "A",
    },
    {
      "id": 9,
      "name": "エンベデッドシステムスペシャリスト",
      "type": "IT・パソコン・情報技術",
      "power": 67,
      "rank": "A",
    },
    {
      "id": 10,
      "name": "CCNP",
      "type": "IT・パソコン・情報技術",
      "power": 65,
      "rank": "A",
    },
    {
      "id": 11,
      "name": "応用情報技術者",
      "type": "IT・パソコン・情報技術",
      "power": 65,
      "rank": "A",
    },
    {
      "id": 12,
      "name": "ディジタル技術検定 １級",
      "type": "IT・パソコン・情報技術",
      "power": 65,
      "rank": "A",
    },
    {
      "id": 13,
      "name": "オラクルマスターゴールド",
      "type": "IT・パソコン・情報技術",
      "power": 65,
      "rank": "A",
    },
    {
      "id": 14,
      "name": "PMP試験",
      "type": "IT・パソコン・情報技術",
      "power": 64,
      "rank": "A",
    },
    {
      "id": 15,
      "name": "XMLマスター ：プロフェッショナル",
      "type": "IT・パソコン・情報技術",
      "power": 64,
      "rank": "A",
    },
    {
      "id": 16,
      "name": "SUN技術者認定資格",
      "type": "IT・パソコン・情報技術",
      "power": 62,
      "rank": "A",
    },
    {
      "id": 17,
      "name": "MCP (上位資格)",
      "type": "IT・パソコン・情報技術",
      "power": 57,
      "rank": "B",
    },
    {
      "id": 18,
      "name": "CG-ARTS検定(CGエンジニア検定 エキスパート）",
      "type": "IT・パソコン・情報技術",
      "power": 55,
      "rank": "B",
    },
    {
      "id": 19,
      "name": "パソコン検定（Ｐ検） １級",
      "type": "IT・パソコン・情報技術",
      "power": 55,
      "rank": "B",
    },
    {
      "id": 20,
      "name": "パソコン整備士１級",
      "type": "IT・パソコン・情報技術",
      "power": 55,
      "rank": "B",
    },
    {
      "id": 21,
      "name": "ディジタル技術検定 ２級",
      "type": "IT・パソコン・情報技術",
      "power": 54,
      "rank": "B",
    },
    {
      "id": 22,
      "name": "ウェブデザイン技能検定 ２級",
      "type": "IT・パソコン・情報技術",
      "power": 54,
      "rank": "B",
    },
    {
      "id": 23,
      "name": "ITコーディネータ",
      "type": "IT・パソコン・情報技術",
      "power": 54,
      "rank": "B",
    },
    {
      "id": 24,
      "name": "オラクルマスターシルバー",
      "type": "IT・パソコン・情報技術",
      "power": 54,
      "rank": "B",
    },
    {
      "id": 25,
      "name": "QuarkXPressクリエイター能力認定試験 １級",
      "type": "IT・パソコン・情報技術",
      "power": 53,
      "rank": "B",
    },
    {
      "id": 26,
      "name": "Linux（LPIＣレベル２）",
      "type": "IT・パソコン・情報技術",
      "power": 53,
      "rank": "B",
    },
    {
      "id": 27,
      "name": "マルチメディア検定（エキスパート）",
      "type": "IT・パソコン・情報技術",
      "power": 52,
      "rank": "B",
    },
    {
      "id": 28,
      "name": "VBAエキスパート （スタンダード）",
      "type": "IT・パソコン・情報技術",
      "power": 52,
      "rank": "B",
    },
    {
      "id": 29,
      "name": "CAD利用技術者試験 １級",
      "type": "IT・パソコン・情報技術",
      "power": 52,
      "rank": "B",
    },
    {
      "id": 30,
      "name": "情報セキュリティ管理士認定試験",
      "type": "IT・パソコン・情報技術",
      "power": 51,
      "rank": "B",
    },
    {
      "id": 31,
      "name": ".com Master ダブルスター",
      "type": "IT・パソコン・情報技術",
      "power": 51,
      "rank": "B",
    },
    {
      "id": 32,
      "name": "MCPC モバイルシステム技術検定 １級",
      "type": "IT・パソコン・情報技術",
      "power": 50,
      "rank": "B",
    },
    {
      "id": 33,
      "name": "基本情報技術者試験",
      "type": "IT・パソコン・情報技術",
      "power": 50,
      "rank": "B",
    },
    {
      "id": 34,
      "name": "情報処理技術者能力認定試験 １級",
      "type": "IT・パソコン・情報技術",
      "power": 50,
      "rank": "B",
    },
    {
      "id": 35,
      "name": "C言語プログラミング能力検定試験",
      "type": "IT・パソコン・情報技術",
      "power": 50,
      "rank": "B",
    },
    {
      "id": 36,
      "name": "ＥＣ(電子商取引)実践能力検定 ２級",
      "type": "IT・パソコン・情報技術",
      "power": 49,
      "rank": "C",
    },
    {
      "id": 37,
      "name": "CG-ARTS検定 (ベーシック)",
      "type": "IT・パソコン・情報技術",
      "power": 48,
      "rank": "C",
    },
    {
      "id": 38,
      "name": "ソフトウェア品質技術者中級",
      "type": "IT・パソコン・情報技術",
      "power": 48,
      "rank": "C",
    },
    {
      "id": 39,
      "name": "情報処理技術者能力認定試験 ２級",
      "type": "IT・パソコン・情報技術",
      "power": 47,
      "rank": "C",
    },
    {
      "id": 40,
      "name": "情報処理技術者能力認定試験 ３級",
      "type": "IT・パソコン・情報技術",
      "power": 47,
      "rank": "C",
    },
    {
      "id": 41,
      "name": "CIW ファンデーション（Web Foundations Associate）",
      "type": "IT・パソコン・情報技術",
      "power": 47,
      "rank": "C",
    },
    {
      "id": 42,
      "name": "XMLマスター ：ベーシック",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 43,
      "name": "ウェブデザイン技能検定 ３級",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 44,
      "name": "文書情報管理士１級",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 45,
      "name": "パソコン検定（Ｐ検）２級",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 46,
      "name": "ソフトウェア品質技術者初級",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 47,
      "name": "MCP(基本資格)",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 48,
      "name": "ITパスポート試験",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 49,
      "name": "情報活用試験（J検） １級",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 50,
      "name": "情報検索応用能力試験 ２級",
      "type": "IT・パソコン・情報技術",
      "power": 46,
      "rank": "C",
    },
    {
      "id": 51,
      "name": "ディジタル技術検定 ３級",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 52,
      "name": "情報システム試験（J検） ＳＥ認定/ＰＧ認定",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 53,
      "name": "CADトレース技能審査 初級・中級",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 54,
      "name": "IT検証技術者認定試験 エントリーレベル１と２",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 55,
      "name": "JSTQB認定テスト技術者資格認定試験 Foundation Level",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 56,
      "name": "情報セキュリティ初級認定試験",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 57,
      "name": "電子メール活用能力検定",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 58,
      "name": "Turbolinux技術者認定試験 Turbo-CE",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 59,
      "name": "VBAエキスパート （ベーシック）",
      "type": "IT・パソコン・情報技術",
      "power": 45,
      "rank": "C",
    },
    {
      "id": 60,
      "name": "文書情報管理士２級",
      "type": "IT・パソコン・情報技術",
      "power": 44,
      "rank": "C",
    },
    {
      "id": 61,
      "name": "Web検定",
      "type": "IT・パソコン・情報技術",
      "power": 44,
      "rank": "C",
    },
    {
      "id": 62,
      "name": "パソコン整備士２級",
      "type": "IT・パソコン・情報技術",
      "power": 44,
      "rank": "C",
    },
    {
      "id": 63,
      "name": "ＥＣ(電子商取引)実践能力検定 ３級",
      "type": "IT・パソコン・情報技術",
      "power": 43,
      "rank": "C",
    },
    {
      "id": 64,
      "name": "情報活用試験（J検）２級",
      "type": "IT・パソコン・情報技術",
      "power": 43,
      "rank": "C",
    },
    {
      "id": 65,
      "name": "MCPC モバイルシステム技術検定 ２級",
      "type": "IT・パソコン・情報技術",
      "power": 43,
      "rank": "C",
    },
    {
      "id": 66,
      "name": "情報デザイン試験（J検）",
      "type": "IT・パソコン・情報技術",
      "power": 42,
      "rank": "C",
    },
    {
      "id": 67,
      "name": "Linux（LPIＣレベル１）",
      "type": "IT・パソコン・情報技術",
      "power": 42,
      "rank": "C",
    },
    {
      "id": 68,
      "name": ".com Master シングルスター",
      "type": "IT・パソコン・情報技術",
      "power": 42,
      "rank": "C",
    },
    {
      "id": 69,
      "name": "CAD利用技術者試験 ２級",
      "type": "IT・パソコン・情報技術",
      "power": 42,
      "rank": "C",
    },
    {
      "id": 70,
      "name": "文書デザイン検定",
      "type": "IT・パソコン・情報技術",
      "power": 39,
      "rank": "D",
    },
    {
      "id": 71,
      "name": "情報活用試験（J検）３級",
      "type": "IT・パソコン・情報技術",
      "power": 39,
      "rank": "D",
    },
    {
      "id": 72,
      "name": "日商ＰＣ検定 ３級",
      "type": "IT・パソコン・情報技術",
      "power": 39,
      "rank": "D",
    },
    {
      "id": 73,
      "name": "マイクロソフト オフィススペシャリストマスター",
      "type": "IT・パソコン・情報技術",
      "power": 38,
      "rank": "D",
    },
    {
      "id": 74,
      "name": "パソコン検定（Ｐ検）３級",
      "type": "IT・パソコン・情報技術",
      "power": 38,
      "rank": "D",
    },
    {
      "id": 75,
      "name": "MCPCケータイ実務検定",
      "type": "IT・パソコン・情報技術",
      "power": 38,
      "rank": "D",
    },
    {
      "id": 76,
      "name": "情報検索基礎能力試験",
      "type": "IT・パソコン・情報技術",
      "power": 37,
      "rank": "D",
    },
    {
      "id": 77,
      "name": "Word/Excel文書処理技能認定試験３級",
      "type": "IT・パソコン・情報技術",
      "power": 37,
      "rank": "D",
    },
    {
      "id": 78,
      "name": "MOS（スペッシャリスト）",
      "type": "IT・パソコン・情報技術",
      "power": 37,
      "rank": "D",
    },
  ];

  Future<void> uploadData() async {
    final collection = FirebaseFirestore.instance.collection('cards');
    for (var card in cards) {
      await collection.add(card);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Data Upload')),
      body: Center(
        child: ElevatedButton(
          onPressed: uploadData,
          child: Text('Upload Data'),
        ),
      ),
    );
  }
}
